//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 10:25:05 AM KST 
//


package com.example.demo.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.demo.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WebInterfaceSubmission_QNAME = new QName("gov/cms/pqrs/patient/v1", "web-interface-submission");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.demo.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WebInterfaceSubmission }
     * 
     */
    public WebInterfaceSubmission createWebInterfaceSubmission() {
        return new WebInterfaceSubmission();
    }

    /**
     * Create an instance of {@link Patient }
     * 
     */
    public Patient createPatient() {
        return new Patient();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WebInterfaceSubmission }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "gov/cms/pqrs/patient/v1", name = "web-interface-submission")
    public JAXBElement<WebInterfaceSubmission> createWebInterfaceSubmission(WebInterfaceSubmission value) {
        return new JAXBElement<WebInterfaceSubmission>(_WebInterfaceSubmission_QNAME, WebInterfaceSubmission.class, null, value);
    }

}
