//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.16 at 10:25:05 AM KST 
//


package com.example.demo.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for patient complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="patient">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="medicare-id" type="{gov/cms/pqrs/patient/v1}medicare-id"/>
 *         &lt;element name="patient-first-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="patient-last-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="birth-date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="medical-record-number" type="{gov/cms/pqrs/patient/v1}string-25char-or-empty" minOccurs="0"/>
 *         &lt;element name="other-id" type="{gov/cms/pqrs/patient/v1}string-20char-or-empty" minOccurs="0"/>
 *         &lt;element name="provider-npi" type="{gov/cms/pqrs/patient/v1}num-10-or-empty" minOccurs="0"/>
 *         &lt;element name="provider-npi-two" type="{gov/cms/pqrs/patient/v1}num-10-or-empty" minOccurs="0"/>
 *         &lt;element name="provider-npi-three" type="{gov/cms/pqrs/patient/v1}num-10-or-empty" minOccurs="0"/>
 *         &lt;element name="clinic-identifier" type="{gov/cms/pqrs/patient/v1}string-9char-or-empty" minOccurs="0"/>
 *         &lt;element name="general-comments" type="{gov/cms/pqrs/patient/v1}string-140char-or-empty" minOccurs="0"/>
 *         &lt;element name="medical-record-found" type="{gov/cms/pqrs/patient/v1}med-rec-fnd-or-empty" minOccurs="0"/>
 *         &lt;element name="medical-not-qualified-reason" type="{gov/cms/pqrs/patient/v1}not-qualif-rea-or-empty" minOccurs="0"/>
 *         &lt;element name="medical-not-qualified-date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="carefalls-rank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="carefalls-confirmed" type="{gov/cms/pqrs/patient/v1}care-confirmed-or-empty" minOccurs="0"/>
 *         &lt;element name="carefalls-rm-ticket" type="{gov/cms/pqrs/patient/v1}string-15char-or-empty" minOccurs="0"/>
 *         &lt;element name="falls-screening" type="{gov/cms/pqrs/patient/v1}exam-or-empty" minOccurs="0"/>
 *         &lt;element name="carefalls-comments" type="{gov/cms/pqrs/patient/v1}string-140char-or-empty" minOccurs="0"/>
 *         &lt;element name="cad-rank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cad-confirmed" type="{gov/cms/pqrs/patient/v1}confirmed-or-empty" minOccurs="0"/>
 *         &lt;element name="cad-rm-ticket" type="{gov/cms/pqrs/patient/v1}string-15char-or-empty" minOccurs="0"/>
 *         &lt;element name="cad-diabetes-lvsd" type="{gov/cms/pqrs/patient/v1}yes-no-or-empty" minOccurs="0"/>
 *         &lt;element name="cad-acearb" type="{gov/cms/pqrs/patient/v1}presc-reason-or-empty" minOccurs="0"/>
 *         &lt;element name="cad-comments" type="{gov/cms/pqrs/patient/v1}string-140char-or-empty" minOccurs="0"/>
 *         &lt;element name="dm-rank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dm-confirmed" type="{gov/cms/pqrs/patient/v1}dm-confirmed-or-empty" minOccurs="0"/>
 *         &lt;element name="dm-rm-ticket" type="{gov/cms/pqrs/patient/v1}string-15char-or-empty" minOccurs="0"/>
 *         &lt;element name="dm-hba1c-test" type="{gov/cms/pqrs/patient/v1}yes-no-or-empty" minOccurs="0"/>
 *         &lt;element name="dm-hba1c-date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dm-hba1c-value" type="{gov/cms/pqrs/patient/v1}decimal-25-or-empty" minOccurs="0"/>
 *         &lt;element name="dm-eye-exam" type="{gov/cms/pqrs/patient/v1}yes-no-or-empty" minOccurs="0"/>
 *         &lt;element name="dm-comments" type="{gov/cms/pqrs/patient/v1}string-140char-or-empty" minOccurs="0"/>
 *         &lt;element name="hf-rank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hf-confirmed" type="{gov/cms/pqrs/patient/v1}confirmed-or-empty" minOccurs="0"/>
 *         &lt;element name="hf-rm-ticket" type="{gov/cms/pqrs/patient/v1}string-15char-or-empty" minOccurs="0"/>
 *         &lt;element name="hf-lvsd" type="{gov/cms/pqrs/patient/v1}yes-no-or-empty" minOccurs="0"/>
 *         &lt;element name="hf-beta-blocker" type="{gov/cms/pqrs/patient/v1}presc-reason-or-empty" minOccurs="0"/>
 *         &lt;element name="hf-comments" type="{gov/cms/pqrs/patient/v1}string-140char-or-empty" minOccurs="0"/>
 *         &lt;element name="htn-rank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="htn-confirmed" type="{gov/cms/pqrs/patient/v1}denominator-confirmed-or-empty" minOccurs="0"/>
 *         &lt;element name="htn-rm-ticket" type="{gov/cms/pqrs/patient/v1}string-15char-or-empty" minOccurs="0"/>
 *         &lt;element name="htn-recent-bp" type="{gov/cms/pqrs/patient/v1}yes-no-or-empty" minOccurs="0"/>
 *         &lt;element name="htn-bp-date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="htn-bp-systolic" type="{gov/cms/pqrs/patient/v1}str-num-350-or-empty" minOccurs="0"/>
 *         &lt;element name="htn-bp-diastolic" type="{gov/cms/pqrs/patient/v1}str-num-200-or-empty" minOccurs="0"/>
 *         &lt;element name="htn-comments" type="{gov/cms/pqrs/patient/v1}string-140char-or-empty" minOccurs="0"/>
 *         &lt;element name="ivd-rank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ivd-confirmed" type="{gov/cms/pqrs/patient/v1}dm-confirmed-or-empty" minOccurs="0"/>
 *         &lt;element name="ivd-rm-ticket" type="{gov/cms/pqrs/patient/v1}string-15char-or-empty" minOccurs="0"/>
 *         &lt;element name="ivd-antithrombotic" type="{gov/cms/pqrs/patient/v1}yes-no-or-empty" minOccurs="0"/>
 *         &lt;element name="ivd-comments" type="{gov/cms/pqrs/patient/v1}string-140char-or-empty" minOccurs="0"/>
 *         &lt;element name="mh-rank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mh-confirmed" type="{gov/cms/pqrs/patient/v1}mh-denom-confirmed-or-empty" minOccurs="0"/>
 *         &lt;element name="mh-rm-ticket" type="{gov/cms/pqrs/patient/v1}string-15char-or-empty" minOccurs="0"/>
 *         &lt;element name="mh-index-performed" type="{gov/cms/pqrs/patient/v1}yes-no-or-empty" minOccurs="0"/>
 *         &lt;element name="mh-index-test" type="{gov/cms/pqrs/patient/v1}yes-no-or-empty" minOccurs="0"/>
 *         &lt;element name="mh-index-date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mh-index-score" type="{gov/cms/pqrs/patient/v1}num-10-27-or-empty" minOccurs="0"/>
 *         &lt;element name="mh-followup-performed" type="{gov/cms/pqrs/patient/v1}yes-no-or-empty" minOccurs="0"/>
 *         &lt;element name="mh-followup-test" type="{gov/cms/pqrs/patient/v1}yes-no-or-empty" minOccurs="0"/>
 *         &lt;element name="mh-followup-date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mh-followup-score" type="{gov/cms/pqrs/patient/v1}num-0-4-or-empty" minOccurs="0"/>
 *         &lt;element name="mh-comments" type="{gov/cms/pqrs/patient/v1}string-140char-or-empty" minOccurs="0"/>
 *         &lt;element name="pcmammogram-rank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pcmammogram-confirmed" type="{gov/cms/pqrs/patient/v1}prev5-not-qualif-or-empty" minOccurs="0"/>
 *         &lt;element name="pcmammogram-rm-ticket" type="{gov/cms/pqrs/patient/v1}string-15char-or-empty" minOccurs="0"/>
 *         &lt;element name="pcmammogram" type="{gov/cms/pqrs/patient/v1}yes-no-or-empty" minOccurs="0"/>
 *         &lt;element name="pcmammogram-comments" type="{gov/cms/pqrs/patient/v1}string-140char-or-empty" minOccurs="0"/>
 *         &lt;element name="pccolorectal-rank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pccolorectal-confirmed" type="{gov/cms/pqrs/patient/v1}prev-den-not-qualif-or-empty" minOccurs="0"/>
 *         &lt;element name="pccolorectal-rm-ticket" type="{gov/cms/pqrs/patient/v1}string-15char-or-empty" minOccurs="0"/>
 *         &lt;element name="pccolorectal" type="{gov/cms/pqrs/patient/v1}yes-no-or-empty" minOccurs="0"/>
 *         &lt;element name="pccolorectal-comments" type="{gov/cms/pqrs/patient/v1}string-140char-or-empty" minOccurs="0"/>
 *         &lt;element name="pcflushot-rank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pcflushot-confirmed" type="{gov/cms/pqrs/patient/v1}prev-other-not-qualif-or-empty" minOccurs="0"/>
 *         &lt;element name="pcflushot-rm-ticket" type="{gov/cms/pqrs/patient/v1}string-15char-or-empty" minOccurs="0"/>
 *         &lt;element name="pcflushot" type="{gov/cms/pqrs/patient/v1}presc-reason-or-empty" minOccurs="0"/>
 *         &lt;element name="pcflushot-comments" type="{gov/cms/pqrs/patient/v1}string-140char-or-empty" minOccurs="0"/>
 *         &lt;element name="pcpneumoshot-rank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pcpneumoshot-confirmed" type="{gov/cms/pqrs/patient/v1}prev-other-not-qualif-or-empty" minOccurs="0"/>
 *         &lt;element name="pcpneumoshot-rm-ticket" type="{gov/cms/pqrs/patient/v1}string-15char-or-empty" minOccurs="0"/>
 *         &lt;element name="pcpneumoshot" type="{gov/cms/pqrs/patient/v1}yes-no-or-empty" minOccurs="0"/>
 *         &lt;element name="pcpneumoshot-comments" type="{gov/cms/pqrs/patient/v1}string-140char-or-empty" minOccurs="0"/>
 *         &lt;element name="pcbmiscreen-rank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pcbmiscreen-confirmed" type="{gov/cms/pqrs/patient/v1}prev-den-not-qualif-or-empty" minOccurs="0"/>
 *         &lt;element name="pcbmiscreen-rm-ticket" type="{gov/cms/pqrs/patient/v1}string-15char-or-empty" minOccurs="0"/>
 *         &lt;element name="pcbmicalculated" type="{gov/cms/pqrs/patient/v1}yes-no-or-empty" minOccurs="0"/>
 *         &lt;element name="pcbminormal" type="{gov/cms/pqrs/patient/v1}yes-no-or-empty" minOccurs="0"/>
 *         &lt;element name="pcbmiplan" type="{gov/cms/pqrs/patient/v1}yes-no-or-empty" minOccurs="0"/>
 *         &lt;element name="pcbmi-comments" type="{gov/cms/pqrs/patient/v1}string-140char-or-empty" minOccurs="0"/>
 *         &lt;element name="pctobaccouse-rank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pctobaccouse-confirmed" type="{gov/cms/pqrs/patient/v1}prev-other-not-qualif-or-empty" minOccurs="0"/>
 *         &lt;element name="pctobaccouse-rm-ticket" type="{gov/cms/pqrs/patient/v1}string-15char-or-empty" minOccurs="0"/>
 *         &lt;element name="pctobaccoscreen" type="{gov/cms/pqrs/patient/v1}prev-screen-or-empty" minOccurs="0"/>
 *         &lt;element name="pctobaccocounsel" type="{gov/cms/pqrs/patient/v1}yes-no-or-empty" minOccurs="0"/>
 *         &lt;element name="pctobaccouse-comments" type="{gov/cms/pqrs/patient/v1}string-140char-or-empty" minOccurs="0"/>
 *         &lt;element name="pcbloodpressure-rank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pcbloodpressure-confirmed" type="{gov/cms/pqrs/patient/v1}prev-den-not-qualif-or-empty" minOccurs="0"/>
 *         &lt;element name="pcbloodpressure-rm-ticket" type="{gov/cms/pqrs/patient/v1}string-15char-or-empty" minOccurs="0"/>
 *         &lt;element name="pcbloodpressure" type="{gov/cms/pqrs/patient/v1}performed-or-empty" minOccurs="0"/>
 *         &lt;element name="pcbpnormal" type="{gov/cms/pqrs/patient/v1}yes-no-or-empty" minOccurs="0"/>
 *         &lt;element name="pcbpfollowup" type="{gov/cms/pqrs/patient/v1}followpup-or-empty" minOccurs="0"/>
 *         &lt;element name="pcbp-comments" type="{gov/cms/pqrs/patient/v1}string-140char-or-empty" minOccurs="0"/>
 *         &lt;element name="pcdepression-rank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pcdepression-confirmed" type="{gov/cms/pqrs/patient/v1}prev-den-not-qualif-or-empty" minOccurs="0"/>
 *         &lt;element name="pcdepression-rm-ticket" type="{gov/cms/pqrs/patient/v1}string-15char-or-empty" minOccurs="0"/>
 *         &lt;element name="pcdepression" type="{gov/cms/pqrs/patient/v1}performed-or-empty" minOccurs="0"/>
 *         &lt;element name="pcdepression-positive" type="{gov/cms/pqrs/patient/v1}yes-no-or-empty" minOccurs="0"/>
 *         &lt;element name="pcdepression-plan" type="{gov/cms/pqrs/patient/v1}yes-no-or-empty" minOccurs="0"/>
 *         &lt;element name="pcdepression-comments" type="{gov/cms/pqrs/patient/v1}string-140char-or-empty" minOccurs="0"/>
 *         &lt;element name="pcstatin-rank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pcstatin-ascvd" type="{gov/cms/pqrs/patient/v1}ascvd-qualif-or-empty" minOccurs="0"/>
 *         &lt;element name="pcstatin-ldlc" type="{gov/cms/pqrs/patient/v1}pc13-qualif-or-empty" minOccurs="0"/>
 *         &lt;element name="pcstatin-diabetes" type="{gov/cms/pqrs/patient/v1}pc13-qualif-or-empty" minOccurs="0"/>
 *         &lt;element name="pcstatin-ldlc-reading" type="{gov/cms/pqrs/patient/v1}ldlc-qualif-or-empty" minOccurs="0"/>
 *         &lt;element name="pcstatin-rm-ticket" type="{gov/cms/pqrs/patient/v1}string-15char-or-empty" minOccurs="0"/>
 *         &lt;element name="pcstatin-prescribed" type="{gov/cms/pqrs/patient/v1}exam-or-empty" minOccurs="0"/>
 *         &lt;element name="pcstatin-comments" type="{gov/cms/pqrs/patient/v1}string-140char-or-empty" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "patient", propOrder = {
    "medicareId",
    "patientFirstName",
    "patientLastName",
    "gender",
    "birthDate",
    "medicalRecordNumber",
    "otherId",
    "providerNpi",
    "providerNpiTwo",
    "providerNpiThree",
    "clinicIdentifier",
    "generalComments",
    "medicalRecordFound",
    "medicalNotQualifiedReason",
    "medicalNotQualifiedDate",
    "carefallsRank",
    "carefallsConfirmed",
    "carefallsRmTicket",
    "fallsScreening",
    "carefallsComments",
    "cadRank",
    "cadConfirmed",
    "cadRmTicket",
    "cadDiabetesLvsd",
    "cadAcearb",
    "cadComments",
    "dmRank",
    "dmConfirmed",
    "dmRmTicket",
    "dmHba1CTest",
    "dmHba1CDate",
    "dmHba1CValue",
    "dmEyeExam",
    "dmComments",
    "hfRank",
    "hfConfirmed",
    "hfRmTicket",
    "hfLvsd",
    "hfBetaBlocker",
    "hfComments",
    "htnRank",
    "htnConfirmed",
    "htnRmTicket",
    "htnRecentBp",
    "htnBpDate",
    "htnBpSystolic",
    "htnBpDiastolic",
    "htnComments",
    "ivdRank",
    "ivdConfirmed",
    "ivdRmTicket",
    "ivdAntithrombotic",
    "ivdComments",
    "mhRank",
    "mhConfirmed",
    "mhRmTicket",
    "mhIndexPerformed",
    "mhIndexTest",
    "mhIndexDate",
    "mhIndexScore",
    "mhFollowupPerformed",
    "mhFollowupTest",
    "mhFollowupDate",
    "mhFollowupScore",
    "mhComments",
    "pcmammogramRank",
    "pcmammogramConfirmed",
    "pcmammogramRmTicket",
    "pcmammogram",
    "pcmammogramComments",
    "pccolorectalRank",
    "pccolorectalConfirmed",
    "pccolorectalRmTicket",
    "pccolorectal",
    "pccolorectalComments",
    "pcflushotRank",
    "pcflushotConfirmed",
    "pcflushotRmTicket",
    "pcflushot",
    "pcflushotComments",
    "pcpneumoshotRank",
    "pcpneumoshotConfirmed",
    "pcpneumoshotRmTicket",
    "pcpneumoshot",
    "pcpneumoshotComments",
    "pcbmiscreenRank",
    "pcbmiscreenConfirmed",
    "pcbmiscreenRmTicket",
    "pcbmicalculated",
    "pcbminormal",
    "pcbmiplan",
    "pcbmiComments",
    "pctobaccouseRank",
    "pctobaccouseConfirmed",
    "pctobaccouseRmTicket",
    "pctobaccoscreen",
    "pctobaccocounsel",
    "pctobaccouseComments",
    "pcbloodpressureRank",
    "pcbloodpressureConfirmed",
    "pcbloodpressureRmTicket",
    "pcbloodpressure",
    "pcbpnormal",
    "pcbpfollowup",
    "pcbpComments",
    "pcdepressionRank",
    "pcdepressionConfirmed",
    "pcdepressionRmTicket",
    "pcdepression",
    "pcdepressionPositive",
    "pcdepressionPlan",
    "pcdepressionComments",
    "pcstatinRank",
    "pcstatinAscvd",
    "pcstatinLdlc",
    "pcstatinDiabetes",
    "pcstatinLdlcReading",
    "pcstatinRmTicket",
    "pcstatinPrescribed",
    "pcstatinComments"
})
public class Patient {

    @XmlElement(name = "medicare-id", required = true)
    protected String medicareId;
    @XmlElement(name = "patient-first-name")
    protected String patientFirstName;
    @XmlElement(name = "patient-last-name")
    protected String patientLastName;
    protected String gender;
    @XmlElement(name = "birth-date")
    protected String birthDate;
    @XmlElement(name = "medical-record-number")
    protected String medicalRecordNumber;
    @XmlElement(name = "other-id")
    protected String otherId;
    @XmlElement(name = "provider-npi")
    protected String providerNpi;
    @XmlElement(name = "provider-npi-two")
    protected String providerNpiTwo;
    @XmlElement(name = "provider-npi-three")
    protected String providerNpiThree;
    @XmlElement(name = "clinic-identifier")
    protected String clinicIdentifier;
    @XmlElement(name = "general-comments")
    protected String generalComments;
    @XmlElement(name = "medical-record-found")
    protected String medicalRecordFound;
    @XmlElement(name = "medical-not-qualified-reason")
    protected String medicalNotQualifiedReason;
    @XmlElement(name = "medical-not-qualified-date")
    protected String medicalNotQualifiedDate;
    @XmlElement(name = "carefalls-rank")
    protected String carefallsRank;
    @XmlElement(name = "carefalls-confirmed")
    protected String carefallsConfirmed;
    @XmlElement(name = "carefalls-rm-ticket")
    protected String carefallsRmTicket;
    @XmlElement(name = "falls-screening")
    protected String fallsScreening;
    @XmlElement(name = "carefalls-comments")
    protected String carefallsComments;
    @XmlElement(name = "cad-rank")
    protected String cadRank;
    @XmlElement(name = "cad-confirmed")
    protected String cadConfirmed;
    @XmlElement(name = "cad-rm-ticket")
    protected String cadRmTicket;
    @XmlElement(name = "cad-diabetes-lvsd")
    protected String cadDiabetesLvsd;
    @XmlElement(name = "cad-acearb")
    protected String cadAcearb;
    @XmlElement(name = "cad-comments")
    protected String cadComments;
    @XmlElement(name = "dm-rank")
    protected String dmRank;
    @XmlElement(name = "dm-confirmed")
    protected String dmConfirmed;
    @XmlElement(name = "dm-rm-ticket")
    protected String dmRmTicket;
    @XmlElement(name = "dm-hba1c-test")
    protected String dmHba1CTest;
    @XmlElement(name = "dm-hba1c-date")
    protected String dmHba1CDate;
    @XmlElement(name = "dm-hba1c-value")
    protected String dmHba1CValue;
    @XmlElement(name = "dm-eye-exam")
    protected String dmEyeExam;
    @XmlElement(name = "dm-comments")
    protected String dmComments;
    @XmlElement(name = "hf-rank")
    protected String hfRank;
    @XmlElement(name = "hf-confirmed")
    protected String hfConfirmed;
    @XmlElement(name = "hf-rm-ticket")
    protected String hfRmTicket;
    @XmlElement(name = "hf-lvsd")
    protected String hfLvsd;
    @XmlElement(name = "hf-beta-blocker")
    protected String hfBetaBlocker;
    @XmlElement(name = "hf-comments")
    protected String hfComments;
    @XmlElement(name = "htn-rank")
    protected String htnRank;
    @XmlElement(name = "htn-confirmed")
    protected String htnConfirmed;
    @XmlElement(name = "htn-rm-ticket")
    protected String htnRmTicket;
    @XmlElement(name = "htn-recent-bp")
    protected String htnRecentBp;
    @XmlElement(name = "htn-bp-date")
    protected String htnBpDate;
    @XmlElement(name = "htn-bp-systolic")
    protected String htnBpSystolic;
    @XmlElement(name = "htn-bp-diastolic")
    protected String htnBpDiastolic;
    @XmlElement(name = "htn-comments")
    protected String htnComments;
    @XmlElement(name = "ivd-rank")
    protected String ivdRank;
    @XmlElement(name = "ivd-confirmed")
    protected String ivdConfirmed;
    @XmlElement(name = "ivd-rm-ticket")
    protected String ivdRmTicket;
    @XmlElement(name = "ivd-antithrombotic")
    protected String ivdAntithrombotic;
    @XmlElement(name = "ivd-comments")
    protected String ivdComments;
    @XmlElement(name = "mh-rank")
    protected String mhRank;
    @XmlElement(name = "mh-confirmed")
    protected String mhConfirmed;
    @XmlElement(name = "mh-rm-ticket")
    protected String mhRmTicket;
    @XmlElement(name = "mh-index-performed")
    protected String mhIndexPerformed;
    @XmlElement(name = "mh-index-test")
    protected String mhIndexTest;
    @XmlElement(name = "mh-index-date")
    protected String mhIndexDate;
    @XmlElement(name = "mh-index-score")
    protected String mhIndexScore;
    @XmlElement(name = "mh-followup-performed")
    protected String mhFollowupPerformed;
    @XmlElement(name = "mh-followup-test")
    protected String mhFollowupTest;
    @XmlElement(name = "mh-followup-date")
    protected String mhFollowupDate;
    @XmlElement(name = "mh-followup-score")
    protected String mhFollowupScore;
    @XmlElement(name = "mh-comments")
    protected String mhComments;
    @XmlElement(name = "pcmammogram-rank")
    protected String pcmammogramRank;
    @XmlElement(name = "pcmammogram-confirmed")
    protected String pcmammogramConfirmed;
    @XmlElement(name = "pcmammogram-rm-ticket")
    protected String pcmammogramRmTicket;
    protected String pcmammogram;
    @XmlElement(name = "pcmammogram-comments")
    protected String pcmammogramComments;
    @XmlElement(name = "pccolorectal-rank")
    protected String pccolorectalRank;
    @XmlElement(name = "pccolorectal-confirmed")
    protected String pccolorectalConfirmed;
    @XmlElement(name = "pccolorectal-rm-ticket")
    protected String pccolorectalRmTicket;
    protected String pccolorectal;
    @XmlElement(name = "pccolorectal-comments")
    protected String pccolorectalComments;
    @XmlElement(name = "pcflushot-rank")
    protected String pcflushotRank;
    @XmlElement(name = "pcflushot-confirmed")
    protected String pcflushotConfirmed;
    @XmlElement(name = "pcflushot-rm-ticket")
    protected String pcflushotRmTicket;
    protected String pcflushot;
    @XmlElement(name = "pcflushot-comments")
    protected String pcflushotComments;
    @XmlElement(name = "pcpneumoshot-rank")
    protected String pcpneumoshotRank;
    @XmlElement(name = "pcpneumoshot-confirmed")
    protected String pcpneumoshotConfirmed;
    @XmlElement(name = "pcpneumoshot-rm-ticket")
    protected String pcpneumoshotRmTicket;
    protected String pcpneumoshot;
    @XmlElement(name = "pcpneumoshot-comments")
    protected String pcpneumoshotComments;
    @XmlElement(name = "pcbmiscreen-rank")
    protected String pcbmiscreenRank;
    @XmlElement(name = "pcbmiscreen-confirmed")
    protected String pcbmiscreenConfirmed;
    @XmlElement(name = "pcbmiscreen-rm-ticket")
    protected String pcbmiscreenRmTicket;
    protected String pcbmicalculated;
    protected String pcbminormal;
    protected String pcbmiplan;
    @XmlElement(name = "pcbmi-comments")
    protected String pcbmiComments;
    @XmlElement(name = "pctobaccouse-rank")
    protected String pctobaccouseRank;
    @XmlElement(name = "pctobaccouse-confirmed")
    protected String pctobaccouseConfirmed;
    @XmlElement(name = "pctobaccouse-rm-ticket")
    protected String pctobaccouseRmTicket;
    protected String pctobaccoscreen;
    protected String pctobaccocounsel;
    @XmlElement(name = "pctobaccouse-comments")
    protected String pctobaccouseComments;
    @XmlElement(name = "pcbloodpressure-rank")
    protected String pcbloodpressureRank;
    @XmlElement(name = "pcbloodpressure-confirmed")
    protected String pcbloodpressureConfirmed;
    @XmlElement(name = "pcbloodpressure-rm-ticket")
    protected String pcbloodpressureRmTicket;
    protected String pcbloodpressure;
    protected String pcbpnormal;
    protected String pcbpfollowup;
    @XmlElement(name = "pcbp-comments")
    protected String pcbpComments;
    @XmlElement(name = "pcdepression-rank")
    protected String pcdepressionRank;
    @XmlElement(name = "pcdepression-confirmed")
    protected String pcdepressionConfirmed;
    @XmlElement(name = "pcdepression-rm-ticket")
    protected String pcdepressionRmTicket;
    protected String pcdepression;
    @XmlElement(name = "pcdepression-positive")
    protected String pcdepressionPositive;
    @XmlElement(name = "pcdepression-plan")
    protected String pcdepressionPlan;
    @XmlElement(name = "pcdepression-comments")
    protected String pcdepressionComments;
    @XmlElement(name = "pcstatin-rank")
    protected String pcstatinRank;
    @XmlElement(name = "pcstatin-ascvd")
    protected String pcstatinAscvd;
    @XmlElement(name = "pcstatin-ldlc")
    protected String pcstatinLdlc;
    @XmlElement(name = "pcstatin-diabetes")
    protected String pcstatinDiabetes;
    @XmlElement(name = "pcstatin-ldlc-reading")
    protected String pcstatinLdlcReading;
    @XmlElement(name = "pcstatin-rm-ticket")
    protected String pcstatinRmTicket;
    @XmlElement(name = "pcstatin-prescribed")
    protected String pcstatinPrescribed;
    @XmlElement(name = "pcstatin-comments")
    protected String pcstatinComments;

    /**
     * Gets the value of the medicareId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicareId() {
        return medicareId;
    }

    /**
     * Sets the value of the medicareId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicareId(String value) {
        this.medicareId = value;
    }

    /**
     * Gets the value of the patientFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientFirstName() {
        return patientFirstName;
    }

    /**
     * Sets the value of the patientFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientFirstName(String value) {
        this.patientFirstName = value;
    }

    /**
     * Gets the value of the patientLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientLastName() {
        return patientLastName;
    }

    /**
     * Sets the value of the patientLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientLastName(String value) {
        this.patientLastName = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthDate(String value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the medicalRecordNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicalRecordNumber() {
        return medicalRecordNumber;
    }

    /**
     * Sets the value of the medicalRecordNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicalRecordNumber(String value) {
        this.medicalRecordNumber = value;
    }

    /**
     * Gets the value of the otherId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherId() {
        return otherId;
    }

    /**
     * Sets the value of the otherId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherId(String value) {
        this.otherId = value;
    }

    /**
     * Gets the value of the providerNpi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderNpi() {
        return providerNpi;
    }

    /**
     * Sets the value of the providerNpi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderNpi(String value) {
        this.providerNpi = value;
    }

    /**
     * Gets the value of the providerNpiTwo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderNpiTwo() {
        return providerNpiTwo;
    }

    /**
     * Sets the value of the providerNpiTwo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderNpiTwo(String value) {
        this.providerNpiTwo = value;
    }

    /**
     * Gets the value of the providerNpiThree property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderNpiThree() {
        return providerNpiThree;
    }

    /**
     * Sets the value of the providerNpiThree property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderNpiThree(String value) {
        this.providerNpiThree = value;
    }

    /**
     * Gets the value of the clinicIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClinicIdentifier() {
        return clinicIdentifier;
    }

    /**
     * Sets the value of the clinicIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClinicIdentifier(String value) {
        this.clinicIdentifier = value;
    }

    /**
     * Gets the value of the generalComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneralComments() {
        return generalComments;
    }

    /**
     * Sets the value of the generalComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneralComments(String value) {
        this.generalComments = value;
    }

    /**
     * Gets the value of the medicalRecordFound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicalRecordFound() {
        return medicalRecordFound;
    }

    /**
     * Sets the value of the medicalRecordFound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicalRecordFound(String value) {
        this.medicalRecordFound = value;
    }

    /**
     * Gets the value of the medicalNotQualifiedReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicalNotQualifiedReason() {
        return medicalNotQualifiedReason;
    }

    /**
     * Sets the value of the medicalNotQualifiedReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicalNotQualifiedReason(String value) {
        this.medicalNotQualifiedReason = value;
    }

    /**
     * Gets the value of the medicalNotQualifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMedicalNotQualifiedDate() {
        return medicalNotQualifiedDate;
    }

    /**
     * Sets the value of the medicalNotQualifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMedicalNotQualifiedDate(String value) {
        this.medicalNotQualifiedDate = value;
    }

    /**
     * Gets the value of the carefallsRank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarefallsRank() {
        return carefallsRank;
    }

    /**
     * Sets the value of the carefallsRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarefallsRank(String value) {
        this.carefallsRank = value;
    }

    /**
     * Gets the value of the carefallsConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarefallsConfirmed() {
        return carefallsConfirmed;
    }

    /**
     * Sets the value of the carefallsConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarefallsConfirmed(String value) {
        this.carefallsConfirmed = value;
    }

    /**
     * Gets the value of the carefallsRmTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarefallsRmTicket() {
        return carefallsRmTicket;
    }

    /**
     * Sets the value of the carefallsRmTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarefallsRmTicket(String value) {
        this.carefallsRmTicket = value;
    }

    /**
     * Gets the value of the fallsScreening property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFallsScreening() {
        return fallsScreening;
    }

    /**
     * Sets the value of the fallsScreening property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFallsScreening(String value) {
        this.fallsScreening = value;
    }

    /**
     * Gets the value of the carefallsComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarefallsComments() {
        return carefallsComments;
    }

    /**
     * Sets the value of the carefallsComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarefallsComments(String value) {
        this.carefallsComments = value;
    }

    /**
     * Gets the value of the cadRank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCadRank() {
        return cadRank;
    }

    /**
     * Sets the value of the cadRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCadRank(String value) {
        this.cadRank = value;
    }

    /**
     * Gets the value of the cadConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCadConfirmed() {
        return cadConfirmed;
    }

    /**
     * Sets the value of the cadConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCadConfirmed(String value) {
        this.cadConfirmed = value;
    }

    /**
     * Gets the value of the cadRmTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCadRmTicket() {
        return cadRmTicket;
    }

    /**
     * Sets the value of the cadRmTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCadRmTicket(String value) {
        this.cadRmTicket = value;
    }

    /**
     * Gets the value of the cadDiabetesLvsd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCadDiabetesLvsd() {
        return cadDiabetesLvsd;
    }

    /**
     * Sets the value of the cadDiabetesLvsd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCadDiabetesLvsd(String value) {
        this.cadDiabetesLvsd = value;
    }

    /**
     * Gets the value of the cadAcearb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCadAcearb() {
        return cadAcearb;
    }

    /**
     * Sets the value of the cadAcearb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCadAcearb(String value) {
        this.cadAcearb = value;
    }

    /**
     * Gets the value of the cadComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCadComments() {
        return cadComments;
    }

    /**
     * Sets the value of the cadComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCadComments(String value) {
        this.cadComments = value;
    }

    /**
     * Gets the value of the dmRank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDmRank() {
        return dmRank;
    }

    /**
     * Sets the value of the dmRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDmRank(String value) {
        this.dmRank = value;
    }

    /**
     * Gets the value of the dmConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDmConfirmed() {
        return dmConfirmed;
    }

    /**
     * Sets the value of the dmConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDmConfirmed(String value) {
        this.dmConfirmed = value;
    }

    /**
     * Gets the value of the dmRmTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDmRmTicket() {
        return dmRmTicket;
    }

    /**
     * Sets the value of the dmRmTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDmRmTicket(String value) {
        this.dmRmTicket = value;
    }

    /**
     * Gets the value of the dmHba1CTest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDmHba1CTest() {
        return dmHba1CTest;
    }

    /**
     * Sets the value of the dmHba1CTest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDmHba1CTest(String value) {
        this.dmHba1CTest = value;
    }

    /**
     * Gets the value of the dmHba1CDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDmHba1CDate() {
        return dmHba1CDate;
    }

    /**
     * Sets the value of the dmHba1CDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDmHba1CDate(String value) {
        this.dmHba1CDate = value;
    }

    /**
     * Gets the value of the dmHba1CValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDmHba1CValue() {
        return dmHba1CValue;
    }

    /**
     * Sets the value of the dmHba1CValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDmHba1CValue(String value) {
        this.dmHba1CValue = value;
    }

    /**
     * Gets the value of the dmEyeExam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDmEyeExam() {
        return dmEyeExam;
    }

    /**
     * Sets the value of the dmEyeExam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDmEyeExam(String value) {
        this.dmEyeExam = value;
    }

    /**
     * Gets the value of the dmComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDmComments() {
        return dmComments;
    }

    /**
     * Sets the value of the dmComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDmComments(String value) {
        this.dmComments = value;
    }

    /**
     * Gets the value of the hfRank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHfRank() {
        return hfRank;
    }

    /**
     * Sets the value of the hfRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHfRank(String value) {
        this.hfRank = value;
    }

    /**
     * Gets the value of the hfConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHfConfirmed() {
        return hfConfirmed;
    }

    /**
     * Sets the value of the hfConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHfConfirmed(String value) {
        this.hfConfirmed = value;
    }

    /**
     * Gets the value of the hfRmTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHfRmTicket() {
        return hfRmTicket;
    }

    /**
     * Sets the value of the hfRmTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHfRmTicket(String value) {
        this.hfRmTicket = value;
    }

    /**
     * Gets the value of the hfLvsd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHfLvsd() {
        return hfLvsd;
    }

    /**
     * Sets the value of the hfLvsd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHfLvsd(String value) {
        this.hfLvsd = value;
    }

    /**
     * Gets the value of the hfBetaBlocker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHfBetaBlocker() {
        return hfBetaBlocker;
    }

    /**
     * Sets the value of the hfBetaBlocker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHfBetaBlocker(String value) {
        this.hfBetaBlocker = value;
    }

    /**
     * Gets the value of the hfComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHfComments() {
        return hfComments;
    }

    /**
     * Sets the value of the hfComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHfComments(String value) {
        this.hfComments = value;
    }

    /**
     * Gets the value of the htnRank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtnRank() {
        return htnRank;
    }

    /**
     * Sets the value of the htnRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtnRank(String value) {
        this.htnRank = value;
    }

    /**
     * Gets the value of the htnConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtnConfirmed() {
        return htnConfirmed;
    }

    /**
     * Sets the value of the htnConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtnConfirmed(String value) {
        this.htnConfirmed = value;
    }

    /**
     * Gets the value of the htnRmTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtnRmTicket() {
        return htnRmTicket;
    }

    /**
     * Sets the value of the htnRmTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtnRmTicket(String value) {
        this.htnRmTicket = value;
    }

    /**
     * Gets the value of the htnRecentBp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtnRecentBp() {
        return htnRecentBp;
    }

    /**
     * Sets the value of the htnRecentBp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtnRecentBp(String value) {
        this.htnRecentBp = value;
    }

    /**
     * Gets the value of the htnBpDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtnBpDate() {
        return htnBpDate;
    }

    /**
     * Sets the value of the htnBpDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtnBpDate(String value) {
        this.htnBpDate = value;
    }

    /**
     * Gets the value of the htnBpSystolic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtnBpSystolic() {
        return htnBpSystolic;
    }

    /**
     * Sets the value of the htnBpSystolic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtnBpSystolic(String value) {
        this.htnBpSystolic = value;
    }

    /**
     * Gets the value of the htnBpDiastolic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtnBpDiastolic() {
        return htnBpDiastolic;
    }

    /**
     * Sets the value of the htnBpDiastolic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtnBpDiastolic(String value) {
        this.htnBpDiastolic = value;
    }

    /**
     * Gets the value of the htnComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtnComments() {
        return htnComments;
    }

    /**
     * Sets the value of the htnComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtnComments(String value) {
        this.htnComments = value;
    }

    /**
     * Gets the value of the ivdRank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIvdRank() {
        return ivdRank;
    }

    /**
     * Sets the value of the ivdRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIvdRank(String value) {
        this.ivdRank = value;
    }

    /**
     * Gets the value of the ivdConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIvdConfirmed() {
        return ivdConfirmed;
    }

    /**
     * Sets the value of the ivdConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIvdConfirmed(String value) {
        this.ivdConfirmed = value;
    }

    /**
     * Gets the value of the ivdRmTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIvdRmTicket() {
        return ivdRmTicket;
    }

    /**
     * Sets the value of the ivdRmTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIvdRmTicket(String value) {
        this.ivdRmTicket = value;
    }

    /**
     * Gets the value of the ivdAntithrombotic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIvdAntithrombotic() {
        return ivdAntithrombotic;
    }

    /**
     * Sets the value of the ivdAntithrombotic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIvdAntithrombotic(String value) {
        this.ivdAntithrombotic = value;
    }

    /**
     * Gets the value of the ivdComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIvdComments() {
        return ivdComments;
    }

    /**
     * Sets the value of the ivdComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIvdComments(String value) {
        this.ivdComments = value;
    }

    /**
     * Gets the value of the mhRank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMhRank() {
        return mhRank;
    }

    /**
     * Sets the value of the mhRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMhRank(String value) {
        this.mhRank = value;
    }

    /**
     * Gets the value of the mhConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMhConfirmed() {
        return mhConfirmed;
    }

    /**
     * Sets the value of the mhConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMhConfirmed(String value) {
        this.mhConfirmed = value;
    }

    /**
     * Gets the value of the mhRmTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMhRmTicket() {
        return mhRmTicket;
    }

    /**
     * Sets the value of the mhRmTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMhRmTicket(String value) {
        this.mhRmTicket = value;
    }

    /**
     * Gets the value of the mhIndexPerformed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMhIndexPerformed() {
        return mhIndexPerformed;
    }

    /**
     * Sets the value of the mhIndexPerformed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMhIndexPerformed(String value) {
        this.mhIndexPerformed = value;
    }

    /**
     * Gets the value of the mhIndexTest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMhIndexTest() {
        return mhIndexTest;
    }

    /**
     * Sets the value of the mhIndexTest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMhIndexTest(String value) {
        this.mhIndexTest = value;
    }

    /**
     * Gets the value of the mhIndexDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMhIndexDate() {
        return mhIndexDate;
    }

    /**
     * Sets the value of the mhIndexDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMhIndexDate(String value) {
        this.mhIndexDate = value;
    }

    /**
     * Gets the value of the mhIndexScore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMhIndexScore() {
        return mhIndexScore;
    }

    /**
     * Sets the value of the mhIndexScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMhIndexScore(String value) {
        this.mhIndexScore = value;
    }

    /**
     * Gets the value of the mhFollowupPerformed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMhFollowupPerformed() {
        return mhFollowupPerformed;
    }

    /**
     * Sets the value of the mhFollowupPerformed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMhFollowupPerformed(String value) {
        this.mhFollowupPerformed = value;
    }

    /**
     * Gets the value of the mhFollowupTest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMhFollowupTest() {
        return mhFollowupTest;
    }

    /**
     * Sets the value of the mhFollowupTest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMhFollowupTest(String value) {
        this.mhFollowupTest = value;
    }

    /**
     * Gets the value of the mhFollowupDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMhFollowupDate() {
        return mhFollowupDate;
    }

    /**
     * Sets the value of the mhFollowupDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMhFollowupDate(String value) {
        this.mhFollowupDate = value;
    }

    /**
     * Gets the value of the mhFollowupScore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMhFollowupScore() {
        return mhFollowupScore;
    }

    /**
     * Sets the value of the mhFollowupScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMhFollowupScore(String value) {
        this.mhFollowupScore = value;
    }

    /**
     * Gets the value of the mhComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMhComments() {
        return mhComments;
    }

    /**
     * Sets the value of the mhComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMhComments(String value) {
        this.mhComments = value;
    }

    /**
     * Gets the value of the pcmammogramRank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcmammogramRank() {
        return pcmammogramRank;
    }

    /**
     * Sets the value of the pcmammogramRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcmammogramRank(String value) {
        this.pcmammogramRank = value;
    }

    /**
     * Gets the value of the pcmammogramConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcmammogramConfirmed() {
        return pcmammogramConfirmed;
    }

    /**
     * Sets the value of the pcmammogramConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcmammogramConfirmed(String value) {
        this.pcmammogramConfirmed = value;
    }

    /**
     * Gets the value of the pcmammogramRmTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcmammogramRmTicket() {
        return pcmammogramRmTicket;
    }

    /**
     * Sets the value of the pcmammogramRmTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcmammogramRmTicket(String value) {
        this.pcmammogramRmTicket = value;
    }

    /**
     * Gets the value of the pcmammogram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcmammogram() {
        return pcmammogram;
    }

    /**
     * Sets the value of the pcmammogram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcmammogram(String value) {
        this.pcmammogram = value;
    }

    /**
     * Gets the value of the pcmammogramComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcmammogramComments() {
        return pcmammogramComments;
    }

    /**
     * Sets the value of the pcmammogramComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcmammogramComments(String value) {
        this.pcmammogramComments = value;
    }

    /**
     * Gets the value of the pccolorectalRank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPccolorectalRank() {
        return pccolorectalRank;
    }

    /**
     * Sets the value of the pccolorectalRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPccolorectalRank(String value) {
        this.pccolorectalRank = value;
    }

    /**
     * Gets the value of the pccolorectalConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPccolorectalConfirmed() {
        return pccolorectalConfirmed;
    }

    /**
     * Sets the value of the pccolorectalConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPccolorectalConfirmed(String value) {
        this.pccolorectalConfirmed = value;
    }

    /**
     * Gets the value of the pccolorectalRmTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPccolorectalRmTicket() {
        return pccolorectalRmTicket;
    }

    /**
     * Sets the value of the pccolorectalRmTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPccolorectalRmTicket(String value) {
        this.pccolorectalRmTicket = value;
    }

    /**
     * Gets the value of the pccolorectal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPccolorectal() {
        return pccolorectal;
    }

    /**
     * Sets the value of the pccolorectal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPccolorectal(String value) {
        this.pccolorectal = value;
    }

    /**
     * Gets the value of the pccolorectalComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPccolorectalComments() {
        return pccolorectalComments;
    }

    /**
     * Sets the value of the pccolorectalComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPccolorectalComments(String value) {
        this.pccolorectalComments = value;
    }

    /**
     * Gets the value of the pcflushotRank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcflushotRank() {
        return pcflushotRank;
    }

    /**
     * Sets the value of the pcflushotRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcflushotRank(String value) {
        this.pcflushotRank = value;
    }

    /**
     * Gets the value of the pcflushotConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcflushotConfirmed() {
        return pcflushotConfirmed;
    }

    /**
     * Sets the value of the pcflushotConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcflushotConfirmed(String value) {
        this.pcflushotConfirmed = value;
    }

    /**
     * Gets the value of the pcflushotRmTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcflushotRmTicket() {
        return pcflushotRmTicket;
    }

    /**
     * Sets the value of the pcflushotRmTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcflushotRmTicket(String value) {
        this.pcflushotRmTicket = value;
    }

    /**
     * Gets the value of the pcflushot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcflushot() {
        return pcflushot;
    }

    /**
     * Sets the value of the pcflushot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcflushot(String value) {
        this.pcflushot = value;
    }

    /**
     * Gets the value of the pcflushotComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcflushotComments() {
        return pcflushotComments;
    }

    /**
     * Sets the value of the pcflushotComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcflushotComments(String value) {
        this.pcflushotComments = value;
    }

    /**
     * Gets the value of the pcpneumoshotRank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcpneumoshotRank() {
        return pcpneumoshotRank;
    }

    /**
     * Sets the value of the pcpneumoshotRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcpneumoshotRank(String value) {
        this.pcpneumoshotRank = value;
    }

    /**
     * Gets the value of the pcpneumoshotConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcpneumoshotConfirmed() {
        return pcpneumoshotConfirmed;
    }

    /**
     * Sets the value of the pcpneumoshotConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcpneumoshotConfirmed(String value) {
        this.pcpneumoshotConfirmed = value;
    }

    /**
     * Gets the value of the pcpneumoshotRmTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcpneumoshotRmTicket() {
        return pcpneumoshotRmTicket;
    }

    /**
     * Sets the value of the pcpneumoshotRmTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcpneumoshotRmTicket(String value) {
        this.pcpneumoshotRmTicket = value;
    }

    /**
     * Gets the value of the pcpneumoshot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcpneumoshot() {
        return pcpneumoshot;
    }

    /**
     * Sets the value of the pcpneumoshot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcpneumoshot(String value) {
        this.pcpneumoshot = value;
    }

    /**
     * Gets the value of the pcpneumoshotComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcpneumoshotComments() {
        return pcpneumoshotComments;
    }

    /**
     * Sets the value of the pcpneumoshotComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcpneumoshotComments(String value) {
        this.pcpneumoshotComments = value;
    }

    /**
     * Gets the value of the pcbmiscreenRank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcbmiscreenRank() {
        return pcbmiscreenRank;
    }

    /**
     * Sets the value of the pcbmiscreenRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcbmiscreenRank(String value) {
        this.pcbmiscreenRank = value;
    }

    /**
     * Gets the value of the pcbmiscreenConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcbmiscreenConfirmed() {
        return pcbmiscreenConfirmed;
    }

    /**
     * Sets the value of the pcbmiscreenConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcbmiscreenConfirmed(String value) {
        this.pcbmiscreenConfirmed = value;
    }

    /**
     * Gets the value of the pcbmiscreenRmTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcbmiscreenRmTicket() {
        return pcbmiscreenRmTicket;
    }

    /**
     * Sets the value of the pcbmiscreenRmTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcbmiscreenRmTicket(String value) {
        this.pcbmiscreenRmTicket = value;
    }

    /**
     * Gets the value of the pcbmicalculated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcbmicalculated() {
        return pcbmicalculated;
    }

    /**
     * Sets the value of the pcbmicalculated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcbmicalculated(String value) {
        this.pcbmicalculated = value;
    }

    /**
     * Gets the value of the pcbminormal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcbminormal() {
        return pcbminormal;
    }

    /**
     * Sets the value of the pcbminormal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcbminormal(String value) {
        this.pcbminormal = value;
    }

    /**
     * Gets the value of the pcbmiplan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcbmiplan() {
        return pcbmiplan;
    }

    /**
     * Sets the value of the pcbmiplan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcbmiplan(String value) {
        this.pcbmiplan = value;
    }

    /**
     * Gets the value of the pcbmiComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcbmiComments() {
        return pcbmiComments;
    }

    /**
     * Sets the value of the pcbmiComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcbmiComments(String value) {
        this.pcbmiComments = value;
    }

    /**
     * Gets the value of the pctobaccouseRank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPctobaccouseRank() {
        return pctobaccouseRank;
    }

    /**
     * Sets the value of the pctobaccouseRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPctobaccouseRank(String value) {
        this.pctobaccouseRank = value;
    }

    /**
     * Gets the value of the pctobaccouseConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPctobaccouseConfirmed() {
        return pctobaccouseConfirmed;
    }

    /**
     * Sets the value of the pctobaccouseConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPctobaccouseConfirmed(String value) {
        this.pctobaccouseConfirmed = value;
    }

    /**
     * Gets the value of the pctobaccouseRmTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPctobaccouseRmTicket() {
        return pctobaccouseRmTicket;
    }

    /**
     * Sets the value of the pctobaccouseRmTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPctobaccouseRmTicket(String value) {
        this.pctobaccouseRmTicket = value;
    }

    /**
     * Gets the value of the pctobaccoscreen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPctobaccoscreen() {
        return pctobaccoscreen;
    }

    /**
     * Sets the value of the pctobaccoscreen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPctobaccoscreen(String value) {
        this.pctobaccoscreen = value;
    }

    /**
     * Gets the value of the pctobaccocounsel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPctobaccocounsel() {
        return pctobaccocounsel;
    }

    /**
     * Sets the value of the pctobaccocounsel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPctobaccocounsel(String value) {
        this.pctobaccocounsel = value;
    }

    /**
     * Gets the value of the pctobaccouseComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPctobaccouseComments() {
        return pctobaccouseComments;
    }

    /**
     * Sets the value of the pctobaccouseComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPctobaccouseComments(String value) {
        this.pctobaccouseComments = value;
    }

    /**
     * Gets the value of the pcbloodpressureRank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcbloodpressureRank() {
        return pcbloodpressureRank;
    }

    /**
     * Sets the value of the pcbloodpressureRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcbloodpressureRank(String value) {
        this.pcbloodpressureRank = value;
    }

    /**
     * Gets the value of the pcbloodpressureConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcbloodpressureConfirmed() {
        return pcbloodpressureConfirmed;
    }

    /**
     * Sets the value of the pcbloodpressureConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcbloodpressureConfirmed(String value) {
        this.pcbloodpressureConfirmed = value;
    }

    /**
     * Gets the value of the pcbloodpressureRmTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcbloodpressureRmTicket() {
        return pcbloodpressureRmTicket;
    }

    /**
     * Sets the value of the pcbloodpressureRmTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcbloodpressureRmTicket(String value) {
        this.pcbloodpressureRmTicket = value;
    }

    /**
     * Gets the value of the pcbloodpressure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcbloodpressure() {
        return pcbloodpressure;
    }

    /**
     * Sets the value of the pcbloodpressure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcbloodpressure(String value) {
        this.pcbloodpressure = value;
    }

    /**
     * Gets the value of the pcbpnormal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcbpnormal() {
        return pcbpnormal;
    }

    /**
     * Sets the value of the pcbpnormal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcbpnormal(String value) {
        this.pcbpnormal = value;
    }

    /**
     * Gets the value of the pcbpfollowup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcbpfollowup() {
        return pcbpfollowup;
    }

    /**
     * Sets the value of the pcbpfollowup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcbpfollowup(String value) {
        this.pcbpfollowup = value;
    }

    /**
     * Gets the value of the pcbpComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcbpComments() {
        return pcbpComments;
    }

    /**
     * Sets the value of the pcbpComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcbpComments(String value) {
        this.pcbpComments = value;
    }

    /**
     * Gets the value of the pcdepressionRank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcdepressionRank() {
        return pcdepressionRank;
    }

    /**
     * Sets the value of the pcdepressionRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcdepressionRank(String value) {
        this.pcdepressionRank = value;
    }

    /**
     * Gets the value of the pcdepressionConfirmed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcdepressionConfirmed() {
        return pcdepressionConfirmed;
    }

    /**
     * Sets the value of the pcdepressionConfirmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcdepressionConfirmed(String value) {
        this.pcdepressionConfirmed = value;
    }

    /**
     * Gets the value of the pcdepressionRmTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcdepressionRmTicket() {
        return pcdepressionRmTicket;
    }

    /**
     * Sets the value of the pcdepressionRmTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcdepressionRmTicket(String value) {
        this.pcdepressionRmTicket = value;
    }

    /**
     * Gets the value of the pcdepression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcdepression() {
        return pcdepression;
    }

    /**
     * Sets the value of the pcdepression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcdepression(String value) {
        this.pcdepression = value;
    }

    /**
     * Gets the value of the pcdepressionPositive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcdepressionPositive() {
        return pcdepressionPositive;
    }

    /**
     * Sets the value of the pcdepressionPositive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcdepressionPositive(String value) {
        this.pcdepressionPositive = value;
    }

    /**
     * Gets the value of the pcdepressionPlan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcdepressionPlan() {
        return pcdepressionPlan;
    }

    /**
     * Sets the value of the pcdepressionPlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcdepressionPlan(String value) {
        this.pcdepressionPlan = value;
    }

    /**
     * Gets the value of the pcdepressionComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcdepressionComments() {
        return pcdepressionComments;
    }

    /**
     * Sets the value of the pcdepressionComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcdepressionComments(String value) {
        this.pcdepressionComments = value;
    }

    /**
     * Gets the value of the pcstatinRank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcstatinRank() {
        return pcstatinRank;
    }

    /**
     * Sets the value of the pcstatinRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcstatinRank(String value) {
        this.pcstatinRank = value;
    }

    /**
     * Gets the value of the pcstatinAscvd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcstatinAscvd() {
        return pcstatinAscvd;
    }

    /**
     * Sets the value of the pcstatinAscvd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcstatinAscvd(String value) {
        this.pcstatinAscvd = value;
    }

    /**
     * Gets the value of the pcstatinLdlc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcstatinLdlc() {
        return pcstatinLdlc;
    }

    /**
     * Sets the value of the pcstatinLdlc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcstatinLdlc(String value) {
        this.pcstatinLdlc = value;
    }

    /**
     * Gets the value of the pcstatinDiabetes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcstatinDiabetes() {
        return pcstatinDiabetes;
    }

    /**
     * Sets the value of the pcstatinDiabetes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcstatinDiabetes(String value) {
        this.pcstatinDiabetes = value;
    }

    /**
     * Gets the value of the pcstatinLdlcReading property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcstatinLdlcReading() {
        return pcstatinLdlcReading;
    }

    /**
     * Sets the value of the pcstatinLdlcReading property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcstatinLdlcReading(String value) {
        this.pcstatinLdlcReading = value;
    }

    /**
     * Gets the value of the pcstatinRmTicket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcstatinRmTicket() {
        return pcstatinRmTicket;
    }

    /**
     * Sets the value of the pcstatinRmTicket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcstatinRmTicket(String value) {
        this.pcstatinRmTicket = value;
    }

    /**
     * Gets the value of the pcstatinPrescribed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcstatinPrescribed() {
        return pcstatinPrescribed;
    }

    /**
     * Sets the value of the pcstatinPrescribed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcstatinPrescribed(String value) {
        this.pcstatinPrescribed = value;
    }

    /**
     * Gets the value of the pcstatinComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPcstatinComments() {
        return pcstatinComments;
    }

    /**
     * Sets the value of the pcstatinComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPcstatinComments(String value) {
        this.pcstatinComments = value;
    }

}
